Sending Patients to ERPNext
Error while Updating Physician :Dhaval Mahesh Shah
Array
(
    [first_name] => Dhaval
    [middle_name] => Mahesh
    [last_name] => Shah
)

Array
(
    [status] => error
    [error] => UnCaught error occured
)

Error while Inserting Item :Test2
Array
(
    [item_code] => 2
    [item_name] => Test2
)

Array
(
    [status] => error
    [error] => Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 119, in handle
    "data": frappe.get_doc(data).insert().as_dict()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 443, in _validate
    self._validate_mandatory()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 710, in _validate_mandatory
    name=self.name))
MandatoryError: [Item, 2]: item_group

)

Error while Inserting Item :Test
Array
(
    [item_code] => 3
    [item_name] => Test
)

Array
(
    [status] => error
    [error] => Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 119, in handle
    "data": frappe.get_doc(data).insert().as_dict()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 443, in _validate
    self._validate_mandatory()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 710, in _validate_mandatory
    name=self.name))
MandatoryError: [Item, 3]: item_group

)

Error while Inserting Item :Test
Array
(
    [item_code] => 5
    [item_name] => Test
)

Array
(
    [status] => error
    [error] => Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 119, in handle
    "data": frappe.get_doc(data).insert().as_dict()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 222, in insert
    self._validate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 443, in _validate
    self._validate_mandatory()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 710, in _validate_mandatory
    name=self.name))
MandatoryError: [Item, 5]: item_group

)

Error while Updating Physician :Dhaval Mahesh Shah
Array
(
    [first_name] => Dhaval
    [middle_name] => Mahesh
    [last_name] => Shah
)

Array
(
    [status] => error
    [error] => UnCaught error occured
)

Synchronization Completed
